all:
  sfTokenAccess:
    param:
      salt:                     my_secrect_salt
      length:                   32
      lifetime:                 30
    cache:
      lifetime:                 60
      prefix:                   token_access
      servers:
        server_01:
          host:                 medialib.reelpeek.dev
          post:                 11211
          persistant:           true